export const places = [
  // RESTAURANTES
  {
    id: 1,
    name: "Outback Steakhouse - Plaza Shopping Itu",
    description: "Restaurante australiano famoso por carnes grelhadas e a icônica Bloomin' Onion.",
    city: "Itu",
    state: "São Paulo",
    street: "Av. Dr. Ermelindo Maffei, 1199",
    additional: "Plaza Shopping Itu",
    businessHours: "11:00 - 22:00",
    tipo: "restaurantes",
  },
  {
    id: 2,
    name: "Pizza da Vila",
    description: "Pizzaria artesanal com ambiente rústico e sabores especiais.",
    city: "Itu",
    state: "São Paulo",
    street: "R. Maestro José Vitório, 52",
    additional: "Jardim Faculdade",
    businessHours: "18:00 - 23:00",
    tipo: "restaurantes",
  },
  {
    id: 3,
    name: "Restaurante Família Menegon",
    description: "Comida caseira e ambiente familiar em um dos restaurantes mais tradicionais da cidade.",
    city: "Itu",
    state: "São Paulo",
    street: "R. Convenção, 139",
    additional: "Centro",
    businessHours: "11:00 - 15:00",
    tipo: "restaurantes",
  },

  // CULTURA
  {
    id: 4,
    name: "Museu Republicano de Itu",
    description: "Museu histórico que conta o início da República no Brasil. Entrada gratuita.",
    city: "Itu",
    state: "São Paulo",
    street: "R. Barão de Itaim, 140",
    additional: "Centro",
    businessHours: "09:00 - 17:00",
    tipo: "cultura",
  },
  {
    id: 5,
    name: "Igreja Matriz Nossa Senhora da Candelária",
    description: "Principal igreja da cidade com arquitetura barroca e história desde 1780.",
    city: "Itu",
    state: "São Paulo",
    street: "Praça da Matriz, s/n",
    additional: "Centro",
    businessHours: "08:00 - 18:00",
    tipo: "cultura",
  },
  {
    id: 6,
    name: "Espaço Fábrica São Luiz",
    description: "Antiga fábrica restaurada com exposições culturais, feiras e eventos.",
    city: "Itu",
    state: "São Paulo",
    street: "R. Paula Souza, 492",
    additional: "Centro",
    businessHours: "10:00 - 18:00",
    tipo: "cultura",
  },

  // NATUREZA
  {
    id: 7,
    name: "Parque do Varvito",
    description: "Parque geológico único no Brasil, com trilhas e formações rochosas raras.",
    city: "Itu",
    state: "São Paulo",
    street: "R. Parque do Varvito, s/n",
    additional: "Nossa Sra. Aparecida",
    businessHours: "09:00 - 17:00",
    tipo: "natureza",
  },
  {
    id: 8,
    name: "Parque Ecológico Taboão",
    description: "Área verde com trilhas leves, lagos e espaços para piquenique.",
    city: "Itu",
    state: "São Paulo",
    street: "Estrada do Taboão, km 1",
    additional: "",
    businessHours: "07:00 - 17:00",
    tipo: "natureza",
  },
  {
    id: 9,
    name: "Praça dos Exageros",
    description: "Praça temática com objetos gigantes, famosa por fotos e lazer ao ar livre.",
    city: "Itu",
    state: "São Paulo",
    street: "Av. Itu 400 Anos, 111",
    additional: "",
    businessHours: "08:00 - 20:00",
    tipo: "natureza",
  },

  // LAZER
  {
    id: 10,
    name: "Cidade da Criança",
    description: "Parque infantil público com brinquedos, pista de caminhada e lazer em família.",
    city: "Itu",
    state: "São Paulo",
    street: "Av. Itu 400 Anos, 77",
    additional: "Bairro Brasil",
    businessHours: "08:00 - 18:00",
    tipo: "lazer",
  },
  {
    id: 11,
    name: "Plaza Shopping Itu",
    description: "Shopping com lojas, cinema, praça de alimentação e eventos.",
    city: "Itu",
    state: "São Paulo",
    street: "Av. Dr. Ermelindo Maffei, 1199",
    additional: "",
    businessHours: "10:00 - 22:00",
    tipo: "lazer",
  },
  {
    id: 12,
    name: "Kartódromo Arena Itu",
    description: "Pista de kart profissional com aluguel de karts e competições.",
    city: "Itu",
    state: "São Paulo",
    street: "Rod. Dep. Archimedes Lammoglia, km 18",
    additional: "",
    businessHours: "14:00 - 22:00",
    tipo: "lazer",
  },
  
  // TURISMO / CULTURA
  {
    id: 13,
    name: "Igreja do Senhor Bom Jesus",
    description: "Igreja histórica do século XVII com belos elementos barrocos e rococós.",
    city: "Itu",
    state: "São Paulo",
    street: "Praça Padre Miguel, s/n",
    additional: "Centro Histórico",
    businessHours: "08:00 - 18:00",
    tipo: "cultura",
  },
  {
    id: 14,
    name: "Museu da Energia de Itu",
    description: "Museu em antiga Casa da Praça sobre história da eletricidade no Brasil.",
    city: "Itu",
    state: "São Paulo",
    street: "Praça Padre Miguel, s/n",
    additional: "Centro",
    businessHours: "Ter a Sex 14:00 - 17:00",
    tipo: "cultura",
  },
  {
    id: 15,
    name: "Espaço Cultural Almeida Jr.",
    description: "Casarão do século XIX, residência dos Barões de Itu, com exposições culturais.",
    city: "Itu",
    state: "São Paulo",
    street: "Rua Barão de Itaim, (varia)",
    additional: "Centro Histórico",
    businessHours: "10:00 - 17:00",
    tipo: "cultura",
  },

  // MONUMENTOS / EXAGEROS
  {
    id: 16,
    name: "Orelhão Gigante e Semáforo Gigante",
    description: "Ícones da Cidade dos Exageros, no entorno da Praça da Matriz.",
    city: "Itu",
    state: "São Paulo",
    street: "Praça Padre Miguel",
    additional: "Centro",
    businessHours: "Sempre aberto",
    tipo: "natureza",
  },
  {
    id: 17,
    name: "Praça da Matriz",
    description: "Praça central do casario colonial, com orelhão e semáforo gigantes.",
    city: "Itu",
    state: "São Paulo",
    street: "Praça Padre Miguel, s/n",
    additional: "Centro",
    businessHours: "Sempre aberto",
    tipo: "natureza",
  },

  // NATUREZA / GEOLÓGICOS
  {
    id: 18,
    name: "Cruzeiro Franciscano",
    description: "Monumento em arenito e varvito, remanescente do conjunto franciscano do século XVIII.",
    city: "Itu",
    state: "São Paulo",
    street: "Eixo Histórico (próx. Praça da Matriz)",
    additional: "",
    businessHours: "Sempre aberto",
    tipo: "cultura",
  },
  {
    id: 19,
    name: "Bosque Alceu Geribello",
    description: "Centro de Educação Ambiental com área verde para trilhas e contato com a natureza.",
    city: "Itu",
    state: "São Paulo",
    street: "Bairro Brasil",
    additional: "",
    businessHours: "Diariamente, 07:00 - 17:00",
    tipo: "natureza",
  },

  // PARQUES & LAZER
  {
    id: 20,
    name: "Fazenda do Chocolate",
    description: "Complexo rural com chocolate artesanal, passeio a cavalo e minifazenda.",
    city: "Itu",
    state: "São Paulo",
    street: "Estr. Eng. Américo de Campos (varia)",
    additional: "",
    businessHours: "09:00 - 17:00",
    tipo: "lazer",
  },
  {
    id: 21,
    name: "Árvore de Natal Gigante",
    description: "Mega estrutura natalina de 84 m erguida anualmente, já foi a maior do mundo.",
    city: "Itu",
    state: "São Paulo",
    street: "Centro (Praça da Matriz)",
    additional: "exposição sazonal",
    businessHours: "Dezembro, 18:00 - 23:00",
    tipo: "lazer",
  },
  {
    id: 22,
    name: "Museu FAMA & Ateliê do Kobra",
    description: "Fábrica restaurada com arte contemporânea, exposições e ateliê do artista Kobra.",
    city: "Itu",
    state: "São Paulo",
    street: "Rua Padre Bartolomeu Tadei, 9",
    additional: "Alto",
    businessHours: "Ter a Dom 10:00 - 17:00",
    tipo: "cultura",
  },
];
